#ifndef TP1_TALLER_CONSTANTS_H
#define TP1_TALLER_CONSTANTS_H

#define EXIT 0
#define RETRY 1
#define MAX_COMMAND_LENGTH 10
#define MAX_INPUT_LENGTH 500

#define INSERT_OPCODE 1
#define DELETE_OPCODE 2
#define SPACE_OPCODE 3
#define NEWLINE_OPCODE 4
#define PRINT_OPCODE 5

#define SHORT_INT true
#define LONG_INT false

#define SUCCESS 0
#define ERROR -1

#endif //TP1_TALLER_CONSTANTS_H
